language: node_js

node_js:
  - 6
  - 8
  - 11

cache:
  directories:
  - $HOME/.npm

addons:
  chrome: stable

script:
  - "testcafe 'path:`/usr/bin/google-chrome-stable` --headless --disable-gpu --remote-debugging-port=9222 --remote-debugging-address=0.0.0.0' $(npm run build) --skip-js-errors --assertion-timeout 30000"

notifications:
  email: false
