language: node_js

node_js:
  - 9
  - 11
  - 12

cache:
  directories:
  - $HOME/.npm

addons:
  chrome: stable

script:
  - "npm run test:ci"
  - "npm run test:e2e"

after_success:
  - "npm run codecov"

notifications:
  email: false
