language: node_js

node_js:
  - 6
  - 9
  - 11
  - 12

cache:
  directories:
  - $HOME/.npm

addons:
  chrome: stable

before_script:
  - '[[ "$(node -v)" =~ v6 ]] && ./sync.sh tests/e2e/steps/*.js || true;'

script:
  - "npm run test:ci"
  - "npm run build -- -- testcafe chrome:headless --color --skip-js-errors --assertion-timeout 30000"

after_success:
  - "npm run codecov"

notifications:
  email: false
