language: node_js

node_js:
  - 6
  - 9
  - 11

cache:
  directories:
  - $HOME/.npm

addons:
  chrome: stable

before_script:
  - testcafe --list-browsers

script:
  - "npm run build -- -- testcafe chrome:headless --color --skip-js-errors --assertion-timeout 30000"

notifications:
  email: false
