language: node_js

node_js:
  - 9
  - 11

cache:
  directories:
  - $HOME/.npm

addons:
  chrome: stable

script:
  - "npm run build -- testcafe 'chrome:headless --disable-gpu --remote-debugging-port=9222 --remote-debugging-address=0.0.0.0' --skip-js-errors --assertion-timeout 30000"

notifications:
  email: false
