language: node_js

node_js:
  - 9
  - 10

cache:
  directories:
  - $HOME/.npm

addons:
  chrome: stable

before_script:
  - "npm i -g testcafe"

script:
  - "npm run test:ci"
  - "npm run test:e2e"

after_success:
  - "npm run codecov"

notifications:
  email: false
